try {
    doSt();
} catch(e: Except) {
    print(e);
} finally {
    print("Yay");
}